### ISSUE TITLE
I'd like to ask you a question，thanks！

### ISSUE THREAD

**Issue by Ysnnnn** [nrjl/gpsoar#1]
when I run 'double_video_thesis' ,it will show that Function or variable 'axlim' is not recognized. And I also can not find the definition of 'axlim'. Would you mind teach me what shoud I do to run this function successfully? Thank you very much!

**Comment by nrjl** [comment]
Yes sorry there was a small mistake that I fixed with #2 . Now you should be able to run GP_sim.m and then run double_thesis_video.m and it should run properly. Let me know if this doesn't work.

**Comment by Ysnnnn** [comment]
> Yes sorry there was a small mistake that I fixed with #2 . Now you should be able to run GP_sim.m and then run double_thesis_video.m and it should run properly. Let me know if this doesn't work.

**Comment by Ysnnnn** [comment]
It works！thank you！Could I know which version of MATLAB are you using？Because when I run GP_sim and double_video_thesis, programs will report the following errors and program can not display all figures.
>> GP_sim

Generating turbulence...
Done.
Point（maybe dot？language of my matlab is not english，I try to translate it.） indexing is not supported for variables of this type.

error getframe>localCheckInsideFigure (line 162)
figPos = parentFig.Position;

error getframe (line 121)
    [offsetRect, withinOuterRect, withinClientRect] =
    localCheckInsideFigure(offsetRect, parentFig);

error GP_sim (line 589)
	if movie_on; M(ii) = getframe(h_fig, [0, 0, 640, 480]);
    end


double_video_thesis
incorrect use getframe (line 125)
Specifies that the rectangle is not fully included in this picture window. MATLAB no longer supports this feature.

error double_video_thesis (line 188)
	M3(ii) = getframe(h_fig, [0, 0, fig_width,
    fig_height]);


I guess maybe Matlab update getframe() function therefore there is errors when I run the program?
Your code help my Graduation Dissertation a lot, thank you again! :)

**Comment by nrjl** [comment]
Yes unfortunately this code is very old (~10 years) and may have started to lose functionality in newer versions of Matlab. I checked with R2020b and did not get the same error, but perhaps the call signature for getframe() has changed? I would probably try to remove the rect specifier and just change the calls to `getframe(h_fig)`, see if that works.

**Comment by Ysnnnn** [comment]
thanks a lot! I will try R2020b.

**Comment by Ysnnnn** [comment]
![微信截图_20220316162610](https://user-images.githubusercontent.com/87028798/158547893-c0c88a79-206b-4f5b-9cab-f5ca812d5dd6.png)
And I don't know this pillar means, does it mean something?

**Comment by nrjl** [comment]
Yes this is the uncertainty colorbar from the GP (the volumetric plot, one sigma in m/s)

**Comment by Ysnnnn** [comment]
thanks. I suddenly remembered a question. In plot_result (line 31).  
cc = max_obs; while CTrain(cc,1)==0; cc=cc-1; end;     There is a error :
The index at position 1 is invalid. The array index must be a positive integer or logical value.
Is this supposed to be cc = max_obs; while CTrain(cc,1)==1; cc=cc-1; end;   The same error show in double_video_thesis(line 122)

**Comment by Ysnnnn** [comment]
I finally run successfully！Thank you for your help and patience！

**Comment by Ysnnnn** [comment]
I finally run successfully！Thank you for your help and patience！

**Comment by nrjl** [comment]
Glad it was useful, all the best with your research!
